# docker-compose.yaml
version: '3.8'
services:

   jenkins:
      container_name: jenkins
      image: jenkins/jenkins:lts
      restart: always
      ports:
      - "8080:8080"
      - "50000:50000"
      volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home:z
      networks:
      - jenkins_net
   
   nginx:
      container_name: nginx
      image: nginx:alpine
      restart: always
      ports:
      - "8081:80"
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
      depends_on:
      - jenkins
      networks:
      - jenkins_net

networks:
   jenkins_net:
      driver: bridge