version: "3.9"
services:

   jenkins:
      container_name: jenkins
      image: jenkins/jenkins:lts
      restart: unless-stopped
      ports:
      - "8080:8080"
# .   Disable the remote agent port:
#     - "50000:50000"
      volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home:z
      networks:
      - jenkins_net
   
   nginx:
      container_name: nginx
      image: nginx:alpine
      restart: unless-stopped
      ports:
      - "8081:80"
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ./nginx/logs:/var/log/nginx
      depends_on:
      - jenkins
      networks:
      - jenkins_net

networks:
   jenkins_net:
      name: nginx_jenkins_network
      driver: bridge